# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.Album'),
            preserve_default=False,
        ),
    ]
