# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_song_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='duation',
            new_name='duration',
        ),
    ]
